Library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('vinyls/', include('vinyls.urls')),
    path('games/', include('games.urls')),
    path('', views.home)
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:books_id>', views.detail, name='detail')
]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:game_id>', views.detail, name='detail') 
]

vinyls/urls.py
from django.urls import path
from . import views

app_name = 'vinyls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:vinyls_id>', views.detail, name='detail')
    ]

books/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    main = models.CharField(max_length=255)
    sub = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.main} {self.sub}'

class Books(models.Model):
    book_id = models.AutoField(primary_key=True)
    language = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    authors = models.CharField(max_length=2040)
    publication_date = models.IntegerField()
    edition = models.CharField(max_length=255)
    picture_url = models.CharField(max_length=2040)
    date_created = models.DateTimeField(default=timezone.now)
    google_books_id = models.CharField(max_length=250)
    
    def __str__(self):
        return self.title

games/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Games(models.Model):
    game_id = models.AutoField(primary_key=True)
    language = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255)
    edition = models.CharField(max_length=255)
    release_year = models.IntegerField()
    picture_url = models.CharField(max_length=2040)
    date_created = models.DateTimeField(default=timezone.now)
    age_range = models.CharField(max_length=255)
    number_players = models.CharField(max_length=255)
    time_of_play = models.CharField(max_length=255)
    board_game_atlas_id = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

#build atlas table store api data?

vinyls/models.py
from django.db import models
from django.utils import timezone


class Genres(models.Model):
    genre = models.CharField(max_length=255)

    def __str__(self):
        return self.genre


class Vinyls(models.Model):
    vinyl_id = models.AutoField(primary_key=True)
    language = models.CharField(max_length=255)
    genre = models.ForeignKey(Genres, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    artists = models.CharField(max_length=255)
    release_year = models.IntegerField()
    picture_url = models.CharField(max_length=2040)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

Library/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Books
from .filters import BookFilter
import requests


app_name = 'books'

def index(request):

    books = Books.objects.all()
    bookFilter = BookFilter(request.GET, queryset=books)
    books = bookFilter.qs
    context = {'books': books, 'bookFilter': bookFilter}
    return render(request, 'books/index.html', context)

def detail(request, books_id):
    book = get_object_or_404(Books, pk=books_id)
    # google books api request
    url = f'https://www.googleapis.com/books/v1/volumes/{book.google_books_id}'
    req = requests.get(url=url)
    google_response = req.json()
    try:
        google_res_desc = google_response['volumeInfo']['description']
    except KeyError:
        google_res_desc = ''
        
    book_main_title = book.title.partition(':')[0]
    book_sub_title = book.title.partition(':')[::-1][0]
    context = {'book': book, 'book_main_title': book_main_title,
               'book_sub_title': book_sub_title, 'google_response': google_response,
               'google_res_desc': google_res_desc}
    return render(request, 'books/detail.html', context)

games/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Games
from .filters import GameFilter
import requests


def atlas_search(game_name):
    client_id = 'T6pBcuPjXQ'
    url = f'https://api.boardgameatlas.com/api/search?name={game_name}&pretty=true&client_id={client_id}'
    req = requests.get(url=url)
    return req.json()

def index(request):
    games = Games.objects.all()
    gameFilter = GameFilter(request.GET, queryset=games)
    games = gameFilter.qs
    context = {'games': games, 'gameFilter': gameFilter}
    return render(request, 'games/index.html', context)


def detail(request, game_id):
    game = get_object_or_404(Games, pk=game_id)
    atlas_json = atlas_search(game.name)
    try:
        atlas_res_desc = atlas_json['games'][0]['description']
    except KeyError:
        atlas_res_desc = ''
    except IndexError:
        atlas_res_desc = ''
        
    context = {'game': game, 'atlas_json': atlas_json, 'atlas_res_desc': atlas_res_desc}
    return render(request, 'games/detail.html', context) 



    

vinyls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Vinyls
from .filters import VinylFilter


app_name = 'vinyls'

def index(request):
    vinyls = Vinyls.objects.all()
    vinylFilter = VinylFilter(request.GET, queryset=vinyls)
    vinyls = vinylFilter.qs
    context = {'vinyls': vinyls, 'vinylFilter': vinylFilter}
    return render (request, 'vinyls/index.html', context)

def detail(request, vinyls_id):
    vinyl = get_object_or_404(Vinyls, pk=vinyls_id)
    context = {'vinyl': vinyl}
    return render(request, 'vinyls/detail.html',context)

books/templates/books/.#detail.html
ajb@pop-os.41596:1628957569

books/templates/books/.#index.html
ajb@pop-os.41596:1628957569

books/templates/books/detail.html
{% extends 'base.html' %}

{% block content %}
<span><h1 > {{book_main_title}} </h1>
<h4> {{book_sub_title}} </h4></span>
</head>
<div id="header" style="height:15%;width:100%;">
  <div style='float:left'>
    <img src={{ book.picture_url }} alt="Image Loading..." style="width:200px;height:235px;"/>
  </div>
  <div style='float:leftt'>
    <table width="400" style="margin-left:10%;float:top;"> 
      <tr>
	<td>Authors: <a>{{ book.authors }}</a></td>
      </tr>
      <tr>
	<td>Published: <a>{{ book.publication_date }}</a></td>
      </tr>
      <tr>
	<td>Language: <a>{{ book.language }}</a></td>
      </tr>
      <tr>
	<td>Aquired: <a>{{ book.date_created }}</a></td>
      </tr>
    </table>
    <a>{{ google_res_desc |safe }}</a>
  </div>
</div>


{% endblock %}

books/templates/books/index.html
{% extends 'base.html' %}

{% block content %}
<form method="get">
{{ bookFilter.form }}
<button class="btn btn-primary" type="submit">
  Search</button>
</form>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Cover</th>
      <th>Category</th>
      <th>Title</th>
      <th>Author(s)</th>
      <th>Year</th>
    </tr>
  </thead>
<tbody>
    {% for book in books %}
    <tr onclick="window.location='{% url 'books:detail' book.book_id %}';">
      <td><img src={{ book.picture_url }} alt="Image Loading..." style="width:74px;height:94px;"></td>
      <td>{{ book.category }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.authors }}</td>
      <td>{{ book.publication_date }}</td>
    <tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

games/templates/games/detail.html
{% extends 'base.html' %}

{% block content %}
<span><h1 > {{game.name}} </h1>
</head>
<div id="header" style="height:15%;width:100%;">
  <div style='float:left'>
    <img src={{ game.picture_url }} alt="Image Loading..." style="width:200px;height:235px;"/>
  </div>
  <div style='float:leftt'>
    <table width="400" style="margin-left:10%;float:top;"> 
      <tr>
	<td>Publisher: <a>{{ game.publisher }}</a></td>
      </tr>
      <tr>
	<td>Year: <a>{{ game.release_year }}</a></td>
      </tr>
      <tr>
	<td>Edition: <a>{{ game.edition }}</a></td>
      </tr>
      <tr>
	<td>Aquired: <a>{{ date.date_created }}</a></td>
      </tr>
    </table>
    <a>{{ atlas_res_desc |safe }}</a>
  </div>
</div>


{% endblock %}

games/templates/games/index.html
{% extends 'base.html' %}

{% block content %}
<form method="get">
{{ gameFilter.form }}
<button class="btn btn-primary" type="submit">
  Search</button>
</form>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Box Art</th>
      <th>Category</th>
      <th>Name</th>
      <th>Publiser</th>
      <th>Year</th>
      <th>Age Range</th>
      <th>Number Players</th>
      <th>Play Time</th>
    </tr>
  </thead>
<tbody>
    {% for game in games %}
    <tr onclick="window.location='{% url "games:detail" game.game_id %}';">
      <td><img src={{ game.picture_url }} alt="Image Loading..." style="width:74px;height:94px;"></td>
      <td>{{ game.category }}</td>
      <td>{{ game.name }}</td>
      <td>{{ game.publisher }}</td>
      <td>{{ game.release_year }}</td>
      <td>{{ game.age_range }} </td>
      <td>{{ game.number_players }}</td>
      <td>{{ game.time_of_play }}</td>
    <tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  <title>Bridges Private Library</title>
  </head>
  <body style="padding-top:50px;">
    <nav class="navbar fixed-top navbar-light bg-light">
      <ul class="nav">
	<li class="nav-item">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/">Home</a>
	  </div>
        </li>
	<li class="nav-item">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'books:index' %}">Books</a>
	  </div>
        </li>
	<li class="nav-item">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'vinyls:index' %}">Vinyls</a>
	  </div>
        </li>
	<li class="nav-item">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'games:index' %}">Games</a>
	  </div>
        </li>
      </ul>
    </nav>
    <main class="container">

      {% block content %}

      {% endblock %}
    </main>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.87.0">
    <title>Album example · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Welcome to the Bridges' Library!</h1>
        <p class="lead text-muted">This project was built to catalog books, vinyls, and games that keep our family and friends entertained. It is hosted with our on premous infostructure. Our development enviorment is hosted on a Dell c8220 unRaid box (or wall art lol). The test and production enviorment live on twin Dell R730xd Proxmox clusters spanning two nodes. We do not have access to 1gb Internet connection yet so....latency might be lack luster.<p>
          <!--a href="#" class="btn btn-primary my-2">Main call to action</a-->
          <!--a href="#" class="btn btn-secondary my-2">Secondary action</a-->
        </p>
      </div>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
	    <img src="https://assets.teenvogue.com/photos/5e6bffbbdee1770008c6d9bd/16:9/w_2560%2Cc_limit/GettyImages-577674005.jpg" alt="Image Loading..." onclick="window.location='{% url 'books:index' %}';" 
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>
            <div class="card-body">
              <p class="card-text">View our book catelog.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='{% url 'books:index' %}';">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='/admin';">Edit</button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
	    <img src="https://economictimes.indiatimes.com/thumb/msid-73612807,width-1200,height-900,resizemode-4,imgsize-212384/vinyl-records_istock.jpg?from=mdr" alt="Loading Image..." onclick="window.location='{% url 'vinyls:index' %}';"
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>

            <div class="card-body">
              <p class="card-text">View our record collection.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='{% url 'vinyls:index' %}';">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='/admin';">Edit</button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
	    <img src="https://specials-images.forbesimg.com/imageserve/5fd2859936891275777bd882/Catan-board-game/960x0.jpg?cropX1=0&cropX2=1500&cropY1=70&cropY2=1433" alt="Loading image...." onclick="window.location='{% url 'games:index' %}';"
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>

            <div class="card-body">
              <p class="card-text">paruse our games.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='{% url 'games:index' %}';">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location='/admin';">Edit</button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>
<script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

      
  </body>
</html>




{% endblock %}

vinyls/templates/vinyls/detail.html
{% extends 'base.html' %}

{% block content %}




<h1> TESTING </h1>
  <div style="float:left;">  <img src={{ vinyl.picture_url }} alt="Image Loading..." style="width:235px;height:235px;"> </div>
  <div style="float:left;"><table style="width:100%;">
      <tbody>
	<tr>
	  <td>Title: <a>{{ vinyl.title }}</a></td>
	</tr>
      </tbody>
    </table>
  </div>

{% endblock %}

vinyls/templates/vinyls/index.html
{% extends 'base.html' %}

{% block content %}
<form method="get">
{{ vinylFilter.form }}
<button class="btn btn-primary" type="submit">
  Search</button>
</form>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Cover</th>
      <th>Genre</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Year</th>
    </tr>
  </thead>
<tbody>
    {% for vinyl in vinyls %}
    <tr onclick="window.location='{% url 'vinyls:detail' vinyl.vinyl_id %}';">
      <td><img src={{ vinyl.picture_url }} alt="Image Loading..." style="width:94px;height:94px;"></td>
      <td>{{ vinyl.genre }}</td>
      <td>{{ vinyl.title }}</td>
      <td>{{ vinyl.artists }}</td>
      <td>{{ vinyl.release_year }}</td>
    <tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});